package dk.softwarehuset.projectmanagement.util;

import static org.junit.Assert.*;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.StringReader;
import java.io.StringWriter;

import dk.softwarehuset.projectmanagement.ui.ApplicationUI;

public class UITestUtil {
	public static void testScreenInteraction(ApplicationUI appUI, String expectedMenu, String input, String expectedOutput, boolean expectedExitStatus) throws IOException {
		// Get each time a new StringWriter, so that each output can be compared in isolation and not as a string containing the output
		// of past interactions.
		StringWriter out = new StringWriter(); 
		
		// Print the menu on the screen.
		appUI.printMenu(new PrintWriter(out));
		
		// Check that the menu contains expectedMenu as substring.
		assertTrue(out.toString().contains(expectedMenu));

		// Read the input from the reader.
		BufferedReader reader = new BufferedReader(new StringReader(input));

		String line = appUI.readInput(reader);
		// Check that the expected selection has been made.
		assertEquals(input,line);
		
		// Process the input.
		out = new StringWriter();
		boolean exit = appUI.processInput(line, new PrintWriter(out));
		// Check for that output generated by the processing the selection, and
		// check that the exit status is the expected one.
		String eol = System.getProperty("line.separator");
		assertEquals(expectedOutput + eol, out.toString());
		assertEquals(expectedExitStatus, exit);
	}
}
